spring:
  profiles:
    active: local
  devtools:
    livereload:
      enabled: false
server:
  port: 8088
--- #local
spring:
  config:
    activate:
      on-profile: local
  logging:
    level:
      root: debug

database:
  hikari:
    jdbc-url: jdbc:log4jdbc:mysql://127.0.0.1:3306/base?useUnicode=yes&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: fpseld1234
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy

--- #dev
spring:
  config:
    activate:
      on-profile: dev
  logging:
    level:
      root: info
--- #prod
spring:
  config:
    activate:
      on-profile: prod
  logging:
    level:
      root: error

